In [2]:
import re
import csv
import time
import sqlite3
# import keyboard
import pandas as pd
from pprint import pprint
from pandas import DataFrame

In [45]:
import pickle 
data = ["ok"]
with open('filename.pickle', 'wb') as file:
    pickle.dump(data, file)

In [3]:
csv.field_size_limit(10_000_000)

131072

In [4]:
conn = sqlite3.connect("fake.db")

In [9]:
cols = [
    'col:ID',
    'col:status',
    'col:scientificName',
    'col:rank',
    'col:originalSpelling',
    'col:uninomial',
    'col:genericName',
    'col:infragenericEpithet',
    'col:specificEpithet',
    'col:infraspecificEpithet',
    'col:code',
    'col:nameStatus',
    'col:environment',
    'col:species',
    'col:subgenus',
    'col:genus',
    'col:subfamily',
    'col:family',
    'col:superfamily',
    'col:suborder',
    'col:order',
    'col:subclass',
    'col:class',
    'col:subphylum',
    'col:phylum',
    'col:kingdom'
]

for rows in pd.read_csv("./obo/NameUsage.tsv", sep="\t", on_bad_lines="skip", engine="python", quoting=3, dtype=str, chunksize=10):
    rows.to_sql(
        "NameUsage",
        conn,
        index=False,
        if_exists="append"
    )
    print(rows.columns)
    break

Index(['col:ID', 'col:alternativeID', 'col:nameAlternativeID', 'col:sourceID',
       'col:parentID', 'col:basionymID', 'col:status', 'col:scientificName',
       'col:authorship', 'col:rank', 'col:notho', 'col:originalSpelling',
       'col:uninomial', 'col:genericName', 'col:infragenericEpithet',
       'col:specificEpithet', 'col:infraspecificEpithet',
       'col:cultivarEpithet', 'col:combinationAuthorship',
       'col:combinationAuthorshipID', 'col:combinationExAuthorship',
       'col:combinationExAuthorshipID', 'col:combinationAuthorshipYear',
       'col:basionymAuthorship', 'col:basionymAuthorshipID',
       'col:basionymExAuthorship', 'col:basionymExAuthorshipID',
       'col:basionymAuthorshipYear', 'col:namePhrase', 'col:nameReferenceID',
       'col:publishedInYear', 'col:publishedInPage', 'col:publishedInPageLink',
       'col:gender', 'col:genderAgreement', 'col:etymology', 'col:code',
       'col:nameStatus', 'col:accordingToID', 'col:accordingToPage',
       'col:accordingToPageLink', 'col:referenceID', 'col:scrutinizer',
       'col:scrutinizerID', 'col:scrutinizerDate', 'col:extinct',
       'col:temporalRangeStart', 'col:temporalRangeEnd', 'col:environment',
       'col:species', 'col:section', 'col:subgenus', 'col:genus',
       'col:subtribe', 'col:tribe', 'col:subfamily', 'col:family',
       'col:superfamily', 'col:suborder', 'col:order', 'col:subclass',
       'col:class', 'col:subphylum', 'col:phylum', 'col:kingdom',
       'col:ordinal', 'col:branchLength', 'col:link', 'col:nameRemarks',
       'col:remarks', 'col:modified', 'col:modifiedBy', 'clb:merged'],
      dtype='object')

In [ ]:
cols = [
    'col:taxonID', 
    'col:name', 
    'col:language'
]

for rows in pd.read_csv("VernacularName.tsv", sep="\t", on_bad_lines="skip", engine="python", quoting=3, dtype=str, usecols=cols, chunksize=100000):
    rows.to_sql(
        "VernacularName",
        conn,
        index=False,
        if_exists="append"
    )

In [ ]:
conn.close()

In [ ]:
accepted_cols = []

for rows in pd.read_csv("VernacularName.tsv", sep="\t", on_bad_lines="skip", engine="python", quoting=3, dtype=str, chunksize=1):
    row = rows.iloc[0]
    for k, v in row.to_dict().items():
        print(k, v)
        if input("Accept:") == 'Y':
            accepted_cols.append(k)

    break

In [ ]:
accepted_cols

In [ ]:
!python -m pip install keyboard
!python -m pip install inflect

In [ ]:
conn = sqlite3.connect("COL.db")

df = pd.read_sql("""
    SELECT 
        n."col:scientificName", 
        v."col:name", 
        v."col:language"
    FROM NameUsage n
    JOIN VernacularName v ON n."col:ID" = v."col:taxonID"
    WHERE 
        n."col:rank" = 'species'
        AND v."col:language" = 'eng'
    LIMIT 10
""", conn)

df

In [ ]:
conn.execute('DROP INDEX IF EXISTS IndexScientificName')
conn.execute('DROP INDEX IF EXISTS IndexName')
conn.execute('DROP INDEX IF EXISTS IndexID')
conn.execute('DROP INDEX IF EXISTS IndexTaxonID')
conn.commit()

In [ ]:

from typing import List, Dict, Tuple, Set, Optional, Union, Literal

In [2]:
conn = sqlite3.connect("COL.db")
cursor = conn.cursor()

In [ ]:
conn.execute('DROP INDEX IndexNameLowerCase')
# conn.execute('CREATE INDEX IF NOT EXISTS IndexNameLowerCase ON VernacularName (LOWER("col:name"))')
# conn.execute('CREATE INDEX IF NOT EXISTS IndexScientificLowerCase ON NameUsage (LOWER("col:scientificName"))')
# conn.execute('CREATE INDEX IF NOT EXISTS IndexScientificNameNoCase ON NameUsage (LOWER("col:scientificName"))')

In [ ]:
# cursor.execute('PRAGMA cache_size = 2000;')

In [12]:
t0 = time.time()
query = """
    SELECT "col:genus"
    FROM NameUsage
    WHERE "col:genus" = "Chaoborus"
    LIMIT 100
"""
print(cursor.execute(query).fetchall())
t1 = time.time()
print(f"{t1-t0}s")

[('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',), ('Chaoborus',)]
3.536628007888794s

In [8]:
t0 = time.time()
query = """
    SELECT *
    FROM VernacularName
    WHERE 
        LOWER("col:name") LIKE '%plant%'
    LIMIT 100
"""
print(cursor.execute(query).fetchone())
t1 = time.time()
print(f"{t1-t0}s")

('6F624', 'plant-sucking nudibranch', 'eng')
0.01239919662475586s

In [ ]:
cursor.execute("PRAGMA index_list('NameUsage')")
print(cursor.fetchall())

In [ ]:
for index in ['IndexRank', 'IndexID', 'IndexScientificName']:
    cursor.execute(f"PRAGMA index_info('{index}')")
    print(index, cursor.fetchall())

In [ ]:
cursor.close()
conn.close()

In [ ]:
def is_abbreviated(name: str) -> Union[str, Tuple[str, str]]:
    if not re.search(r"[A-Za-z]\.\s[A-Z-a-z]+", name):
        return False
    return name.split()

def find_scientific_name_query(name: Union[str, Tuple[str, str]], only_species=True):
    where_species = "" if not only_species else 'AND NameUsage."col:rank" = \'species\''
    where = None
    if isinstance(name, str):
        where = f'WHERE NameUsage."col:scientificName" LIKE \'{name}\''
    else:
        where = f'WHERE SUBSTR(NameUsage."col:genericName", 1, 1) LIKE \'{name[0][0]}\' AND NameUsage."col:specificEpithet" LIKE \'{name[1]}\''
    
    return f"""
        SELECT *
        FROM NameUsage
        {where}
        {where_species}
    """

def find_vernacular_name_query(name: str, only_english=False):
    where_english = "" if not only_english else 'AND VernacularName."col:language" = \'eng\''
    
    return f"""
        SELECT *
        FROM VernacularName
        WHERE VernacularName."col:name" LIKE '{name}'
        {where_english}
    """

def find_scientific_name_subs_query(name: Union[str, Tuple[str, str]], only_species=True, only_english=False):
    where = None
    if isinstance(name, str):
        where = f'WHERE NameUsage."col:scientificName" LIKE \'{name}\''
    else:
        where = f'WHERE SUBSTR(NameUsage."col:genericName", 1, 1) LIKE \'{name[0][0]}\' AND NameUsage."col:specificEpithet" LIKE \'{name[1]}\''

    where_species = "" if not only_species else 'AND NameUsage."col:rank" = \'species\''
    where_english = "" if not only_english else 'AND VernacularName."col:language" = \'eng\''
    
    return f"""
        SELECT *
        FROM NameUsage
        JOIN VernacularName 
        ON NameUsage."col:ID" = VernacularName."col:taxonID"
        {where}
        {where_species}
        {where_english}
    """

def find_vernacular_name_subs_query(name: str, only_species=True, only_english=False):
    where_species = "" if not only_species else 'AND NameUsage."col:rank" = \'species\''
    where_english = "" if not only_english else 'AND VernacularName."col:language" = \'eng\''
    
    return f"""
        SELECT NameUsage.*, VernacularName.*
        FROM NameUsage
        JOIN VernacularName 
        ON NameUsage."col:ID" = VernacularName."col:taxonID"
        WHERE VernacularName."col:name" LIKE '{name}'
        {where_species}
        {where_english}
    """

def search_scientific_name(name: str) -> DataFrame:
    binomial = is_abbreviated(name) or name
    query = find_scientific_name_query(binomial)
    print(query)
    return pd.read_sql(query, conn)

def search_vernacular_name(name: str) -> DataFrame:
    query = find_vernacular_name_query(name)
    return pd.read_sql(query, conn)

def find_scientific_name_substitutions(name: str) -> list[str]:
    name = is_abbreviated(name) or name
    query = find_scientific_name_subs_query(name)
    output = pd.read_sql(query, conn)
    
    # Get Substitutions
    output = output["col:name"].tolist()
    output = [text.lower() for text in output]
    output = [*set(output)]
    
    return output
    
def find_vernacular_name_substitutions(name: str):
    query = find_vernacular_name_subs_query(name)
    output = pd.read_sql(query, conn)

    # Get Substitutions
    output = search_name(name)
    output = output["col:scientificName"].tolist()
    output = [text.lower() for text in output]
    output = [*set(output)]
    
    return output

In [ ]:
name = "S. aterrimus"
output = find_scientific_name_substitutions(name)
output

In [40]:
pd.read_sql(f"""
    SELECT
        "col:name"
    FROM VernacularName
    WHERE 
        "col:name" LIKE 'zooplankton'
    LIMIT 100
""", conn)

Empty DataFrame
Columns: [col:name]
Index: []

In [24]:
conn.execute('CREATE INDEX IF NOT EXISTS IndexGenusLowerCase ON NameUsage (LOWER("col:genus"))')

In [38]:
df = pd.read_sql(f"""
    SELECT * 
    FROM NameUsage
    WHERE LOWER("col:genus") = LOWER('the')
    LIMIT 1
""", conn)

In [39]:
df

,col:ID,col:status,col:scientificName,col:rank,col:originalSpelling,col:uninomial,col:genericName,col:infragenericEpithet,col:specificEpithet,col:infraspecificEpithet,...,col:subfamily,col:family,col:superfamily,col:suborder,col:order,col:subclass,col:class,col:subphylum,col:phylum,col:kingdom
0,TZPVD,provisionally accepted,The scirpioides,species,None,None,The,None,scirpioides,None,...,None,Thesiaceae,None,None,Santalales,None,Magnoliopsida,None,Tracheophyta,Plantae

In [ ]:
t0 = time.time()
output = search_scientific_name("Oscarella lobularis")
print(output.shape)
t1 = time.time()

print(f"{t1 - t0}s")

In [ ]:
t0 = time.time()
output = search_scientific_name("Oscarella lobularis")
print(output.shape)
t1 = time.time()

print(f"{t1 - t0}s")

In [ ]:
t0 = time.time()
output = search_scientific_name("Oscarella lobularis")
print(output.shape)
t1 = time.time()

print(f"{t1 - t0}s")

In [ ]:
t0 = time.time()
output = search_scientific_name("Panthera leo")
print(output.shape)
t1 = time.time()

print(f"{t1 - t0}s")

In [ ]:
t0 = time.time()
output = search_scientific_name("Panthera leo")
print(output.shape)
t1 = time.time()

print(f"{t1 - t0}s")

In [ ]:
t0 = time.time()
output = search_scientific_name("Panthera leo")
print(output.shape)
t1 = time.time()

print(f"{t1 - t0}s")

In [ ]:
conn.execute('CREATE INDEX IF NOT EXISTS IndexID ON NameUsage ("col:ID")')
conn.execute('CREATE INDEX IF NOT EXISTS IndexRank ON NameUsage ("col:rank")')
conn.execute('CREATE INDEX IF NOT EXISTS IndexName ON VernacularName ("col:name")')
conn.execute('CREATE INDEX IF NOT EXISTS IndexTaxonID ON VernacularName ("col:taxonID")')
conn.execute('CREATE INDEX IF NOT EXISTS IndexLanguage ON VernacularName ("col:language")')
conn.execute('CREATE INDEX IF NOT EXISTS IndexScientificName ON NameUsage ("col:scientificName")')
conn.commit()

In [ ]:
t0 = time.time()
output = search_scientific_name("Oscarella lobularis")
print(output.shape)
t1 = time.time()

print(f"{t1 - t0}s")

In [ ]:
t0 = time.time()
output = search_scientific_name("Oscarella lobularis")
print(output.shape)
t1 = time.time()

print(f"{t1 - t0}s")

In [ ]:
t0 = time.time()
output = search_scientific_name("Oscarella lobularis")
print(output.shape)
t1 = time.time()

print(f"{t1 - t0}s")

In [ ]:
t0 = time.time()
output = search_scientific_name("Panthera leo")
print(output.shape)
t1 = time.time()

print(f"{t1 - t0}s")

In [ ]:
t0 = time.time()
output = search_scientific_name("Panthera leo")
print(output.shape)
t1 = time.time()

print(f"{t1 - t0}s")

In [ ]:
t0 = time.time()
output = search_scientific_name("Panthera leo")
print(output.shape)
t1 = time.time()

print(f"{t1 - t0}s")

In [ ]:
conn.close()

In [ ]:
import inflect
inflector = inflect.engine()

In [ ]:
inflector.singular_noun("mice")

In [ ]:
!python -m pip install rich
!python -m pip install "rich[jupyter]"

In [ ]:
import re
from rich.console import Console

console = Console()

def highlight(string, substrings):
    for substring in substrings:
        string = re.sub(f"({re.escape(substring)})", r"[bold black on bright_yellow]\1[/bold black on bright_yellow]", string, flags=re.IGNORECASE)
    console.print(string)

highlight("The quick brown fox jumps over the lazy dog", ["fox", "dog"])